return {
    {
        "pwntester/octo.nvim",
        cmd = "Octo",
        dependencies = {
            "nvim-lua/plenary.nvim",
            "folke/snacks.nvim",
        },
        opts = {
            picker = "snacks",
            enable_builtin = true,
            default_merge_method = "squash",
            file_panel = { icons = false },
            ui = { use_signcolumn = true },
            use_local_fs = true,
            mappings_disable_default = true,
            mappings = {
                pull_request = {
                    checkout_pr = { lhs = "<localleader>po", desc = "checkout PR" },
                    goto_file   = { lhs = "gf",              desc = "go to file" },
                },
                review_diff = {
                    add_review_comment      = { lhs = "<localleader>ca",      desc = "add review comment", mode = { "n", "x" } },
                    select_next_entry       = { lhs = "]q",                   desc = "move to next changed file" },
                    select_prev_entry       = { lhs = "[q",                   desc = "move to previous changed file" },
                    select_first_entry      = { lhs = "[Q",                   desc = "move to first changed file" },
                    select_last_entry       = { lhs = "]Q",                   desc = "move to last changed file" },
                    select_next_unviewed_entry = { lhs = "]u",                desc = "move to next unviewed file" },
                    select_prev_unviewed_entry = { lhs = "[u",                desc = "move to previous unviewed file" },
                    toggle_viewed           = { lhs = "<localleader><space>", desc = "toggle viewer viewed state" },
                    focus_files             = { lhs = "<localleader>e",       desc = "move focus to changed file panel" },
                    toggle_files            = { lhs = "<localleader>b",       desc = "hide/show changed files panel" },
                    close_review_tab        = { lhs = "<C-c>",                desc = "close review tab" },
                    goto_file               = { lhs = "gf",                   desc = "go to file" },
                },
                file_panel = {
                    next_entry              = { lhs = "j",                    desc = "move to next changed file" },
                    prev_entry              = { lhs = "k",                    desc = "move to previous changed file" },
                    select_entry            = { lhs = "<cr>",                 desc = "show selected changed file diffs" },
                    refresh_files           = { lhs = "R",                    desc = "refresh changed files panel" },
                    select_next_entry       = { lhs = "]q",                   desc = "move to next changed file" },
                    select_prev_entry       = { lhs = "[q",                   desc = "move to previous changed file" },
                    select_first_entry      = { lhs = "[Q",                   desc = "move to first changed file" },
                    select_last_entry       = { lhs = "]Q",                   desc = "move to last changed file" },
                    select_next_unviewed_entry = { lhs = "]u",                desc = "move to next unviewed file" },
                    select_prev_unviewed_entry = { lhs = "[u",                desc = "move to previous unviewed file" },
                    toggle_viewed           = { lhs = "<localleader><space>", desc = "toggle viewer viewed state" },
                    focus_files             = { lhs = "<localleader>e",       desc = "move focus to changed file panel" },
                    toggle_files            = { lhs = "<localleader>b",       desc = "hide/show changed files panel" },
                    close_review_tab        = { lhs = "<C-c>",                desc = "close review tab" },
                },
                review_thread = {
                    select_next_entry       = { lhs = "]q",                   desc = "move to next changed file" },
                    select_prev_entry       = { lhs = "[q",                   desc = "move to previous changed file" },
                    select_first_entry      = { lhs = "[Q",                   desc = "move to first changed file" },
                    select_last_entry       = { lhs = "]Q",                   desc = "move to last changed file" },
                    select_next_unviewed_entry = { lhs = "]u",                desc = "move to next unviewed file" },
                    select_prev_unviewed_entry = { lhs = "[u",                desc = "move to previous unviewed file" },
                    close_review_tab        = { lhs = "<C-c>",                desc = "close review tab" },
                },
                submit_win = {
                    approve_review   = { lhs = "<C-a>", desc = "approve review",         mode = { "n" } },
                    comment_review   = { lhs = "<C-m>", desc = "comment review",         mode = { "n" } },
                    request_changes  = { lhs = "<C-r>", desc = "request changes review", mode = { "n" } },
                    close_review_tab = { lhs = "<C-c>", desc = "close review tab",       mode = { "n" } },
                },
            },
        },
        keys = {
            { "<leader>go", "<cmd>Octo<cr>",                   desc = "Octo actions" },
            { "<leader>gi", "<cmd>Octo issue list<cr>",        desc = "Octo: list issues" },
            { "<leader>gp", "<cmd>Octo pr list<cr>",           desc = "Octo: list PRs" },
            { "<leader>gs", "<cmd>Octo search<cr>",            desc = "Octo: search" },
            { "<leader>gr", "<cmd>Octo review<cr>",            desc = "Octo: review" },
            { "<leader>gn", "<cmd>Octo notification list<cr>", desc = "Octo: notifications" },
        },
    },
}
